Thanks for contributing to the Cookbook. Please follow these
guidelines. Some are only a convention, some are important for epub
generation.

** Titles
   :PROPERTIES:
   :CUSTOM_ID: titles
   :END:

- (important) the first section in a chapter should be a subsection: =## title= (indeed, the section name in the epub is the chapter name).

- titles are like a sentence, only the first word is capitalized.

- if you refer to functions, use markdown syntax too (backtics).

** Lists
   :PROPERTIES:
   :CUSTOM_ID: lists
   :END:

- numbered bullet lists (=1.=) should be used only at the first level. For the next nested levels, use normal non-numbered lists.

** Code formatting
   :PROPERTIES:
   :CUSTOM_ID: code-formatting
   :END:

- functions should generally be referenced with backtics. There is no need to capitalize them in the age of markdown: write =function= instead of FUNCTION.

** Code snippets
   :PROPERTIES:
   :CUSTOM_ID: code-snippets
   :END:

- use =~~~lisp= for code snippets.

- snippets must start at the beginning of a line. Don't indent the =~~~lisp= code fence.

- code snippets must be preceded and followed by a newline:

#+BEGIN_EXAMPLE

  Here's a snippet:

  ~~~lisp
  (defun oh ())
  ~~~

  This snippet...
#+END_EXAMPLE

- to show a snippet's result, use =;; => result= on the same line if the snippet was on one line, otherwise you can do:

#+BEGIN_SRC lisp
  (print :abc)
  ;; :abc
#+END_SRC

If the result is large, use another code block, without comments.
